# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PDFKit-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'EZSwiftExtensions', '~> 1.10'
  pod 'SnapKit', '~> 3.2'
  # Pods for PDFKit-iOS

end
